sudo: required

language: python
python:
  - "3.5"

cache:
  - pip

services:
  - docker

before_install:
  - docker build -t thiagofigueiro/varnish-alpine-docker:ci .
  - sudo service docker restart ; sleep 5

install: "pip install -r requirements.txt"

script:
  - py.test --junitxml=junit.xml --color=yes -v
